services:
  caddy-preview: # caddy-preview 컨테이너
    image: caddy:2.8.4
    container_name: caddy-preview
    ports:
      - "18080:80" # 호스트의 18080 포트를 컨테이너의 80 포트에 매핑
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped 
    networks:
      - webnet 

networks:
  webnet: 
    external: true # 기존 webnet 네트워크 사용
